color: null
fieldLayouts:
  9be0e907-5cc2-451c-b457-be3358c1b4d6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d9fb5230-7bf0-4713-b2e5-a3763cee477e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7bf7da79-8f7d-4a1b-8129-121b24c0d99b # Hero - Standard Hero - Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e55be1a7-e5f5-4dd9-ab8f-20059e00de10
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 573e7c5c-3f4a-4007-abac-659fb790ec6d
        userCondition: null
handle: heroImage
hasTitleField: false
icon: ''
name: HeroImage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
