columnSuffix: null
contentColumnType: string
handle: hero
instructions: null
name: Hero
searchable: false
settings:
  entryTypes:
    - 120a7750-0967-496d-9315-bba6d83eb4b1 # Standard Hero
    - 323e9af3-aa75-4f1c-82eb-370e40179f41 # Slider Hero
    - b4d947dc-370e-4404-807b-b165534a1503 # Basic Hero
  maxEntries: 1
  minEntries: 1
  propagationKeyFormat: null
  propagationMethod: none
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
