columnSuffix: null
handle: slides
instructions: null
name: 'Hero - Slider Hero - Slides'
searchable: false
settings:
  contentTable: ''
  createButtonLabel: null
  entryTypes:
    - 120a7750-0967-496d-9315-bba6d83eb4b1 # Standard Hero
  includeTableView: false
  maxEntries: 5
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: none
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
